AWSTemplateFormatVersion: '2010-09-09'
Description: 'BudgetBuddy Backend - AWS Secrets Manager Secrets'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Deployment environment

Resources:
  # JWT Secret
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'budgetbuddy/${Environment}/jwt-secret'
      Description: JWT signing secret for authentication tokens
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: 'jwtSecret'
        PasswordLength: 64
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: budgetbuddy-backend
        - Key: ManagedBy
          Value: CloudFormation

  # Plaid Secrets
  PlaidSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'budgetbuddy/${Environment}/plaid'
      Description: Plaid API credentials (clientId, secret, environment)
      SecretString: !Sub |
        {
          "clientId": "",
          "secret": "",
          "environment": "sandbox"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: budgetbuddy-backend
        - Key: ManagedBy
          Value: CloudFormation

  # Stripe Secrets
  StripeSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'budgetbuddy/${Environment}/stripe'
      Description: Stripe API credentials (secretKey, publishableKey)
      SecretString: !Sub |
        {
          "secretKey": "",
          "publishableKey": ""
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: budgetbuddy-backend
        - Key: ManagedBy
          Value: CloudFormation

  # Database Configuration (for reference, if needed)
  DatabaseConfigSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'budgetbuddy/${Environment}/database'
      Description: Database configuration (endpoint, port, etc.)
      SecretString: !Sub |
        {
          "endpoint": "",
          "port": "5432",
          "database": "budgetbuddy"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: budgetbuddy-backend
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  JWTSecretArn:
    Description: ARN of the JWT secret
    Value: !Ref JWTSecret
    Export:
      Name: !Sub '${AWS::StackName}-JWTSecretArn'
  
  PlaidSecretArn:
    Description: ARN of the Plaid secret
    Value: !Ref PlaidSecret
    Export:
      Name: !Sub '${AWS::StackName}-PlaidSecretArn'
  
  StripeSecretArn:
    Description: ARN of the Stripe secret
    Value: !Ref StripeSecret
    Export:
      Name: !Sub '${AWS::StackName}-StripeSecretArn'

